### ISSUE TITLE
setup_env.sh not working properly on Mac OS

### ISSUE THREAD

**Issue by justinlent** [sigopt/sigopt-examples#15]
I just tried re-setting up from scratch on a faster computer.  Doesn't seem like setup_env.sh actually takes the "Darwin" path on Mac (eventhough when I run `uname -s ` on the command line I see 'Darwin').  

As well, `brew install gfortran` has been deprecated in favor of `brew install gcc` it seems.

Seems as though by running most of these steps manually and then re-running setup_env.sh I get things to work, but I'm definitely not a bash expert, or a python package requirements install expert 

Another wrinkle depending on your homebrew you may have to supply the gcc version in the brew install

```
Error: No available formula for gcc
GCC is now maintained in homebrew-versions, with major version
number in formula name as suffix. Please tap using:

    brew tap homebrew/versions

and then install GCC based on its version, e.g., 'brew install gcc47'.
```
However, if I run `brew update` first, then the simple approach works, `brew install gcc`

Probably not worth racking brains about, but worth considering in future setup scripts

**Comment by alexandraj777** [comment]
cc @iandewancker

**Comment by pfhayes** [comment]
I've fixed the OS check in https://github.com/sigopt/sigopt-examples/pull/16

**Comment by justinlent** [comment]
great!
